# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

symm_distance_matrix <- function(m1) {
    .Call('_apgpbart_symm_distance_matrix', PACKAGE = 'apgpbart', m1)
}

distance_matrix <- function(m1, m2) {
    .Call('_apgpbart_distance_matrix', PACKAGE = 'apgpbart', m1, m2)
}

